"""AUTO-GENERATED from contracts.yaml - DO NOT EDIT
Generated by mycelium-protocol codegen.
Edit contracts.yaml and rerun code generation.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import ClassVar, List

from mycelium.protocol.runtime import (
    FieldDef,
    FixedBytes,
    FixedStr,
    FixedVecBytes,
    MessageDef,
    Primitive,
    register_message,
)

__all__ = ["BatchOperation", "CounterUpdate", "TextMessage"]

@dataclass
class BatchOperation:
    """Batch of operations (domain: Examples)"""

    TYPE_ID: ClassVar[int] = 1003
    TOPIC: ClassVar[str] = "examples"
    __definition__: ClassVar[MessageDef]

    operation_id: int
    items: List[bytes]
    total_count: int

    def to_bytes(self) -> bytes:
        return self.__definition__.encode(self)

    @classmethod
    def from_bytes(cls, payload: bytes) -> "BatchOperation":
        return cls.__definition__.decode(cls, payload)

BatchOperation.__definition__ = MessageDef(
    name="BatchOperation",
    type_id=1003,
    topic="examples",
    fields=[
        FieldDef("operation_id", Primitive.U64),
        FieldDef("items", FixedVecBytes(element_size=0, capacity=10)),
        FieldDef("total_count", Primitive.U32),
    ],
    dataclass=BatchOperation,
)
register_message(BatchOperation.__definition__)

@dataclass
class CounterUpdate:
    """Counter increment/decrement (domain: Examples)"""

    TYPE_ID: ClassVar[int] = 1002
    TOPIC: ClassVar[str] = "examples"
    __definition__: ClassVar[MessageDef]

    counter_id: int
    value: int
    delta: int

    def to_bytes(self) -> bytes:
        return self.__definition__.encode(self)

    @classmethod
    def from_bytes(cls, payload: bytes) -> "CounterUpdate":
        return cls.__definition__.decode(cls, payload)

CounterUpdate.__definition__ = MessageDef(
    name="CounterUpdate",
    type_id=1002,
    topic="examples",
    fields=[
        FieldDef("counter_id", Primitive.U64),
        FieldDef("value", Primitive.I32),
        FieldDef("delta", Primitive.I32),
    ],
    dataclass=CounterUpdate,
)
register_message(CounterUpdate.__definition__)

@dataclass
class TextMessage:
    """Simple text message (domain: Examples)"""

    TYPE_ID: ClassVar[int] = 1001
    TOPIC: ClassVar[str] = "examples"
    __definition__: ClassVar[MessageDef]

    sender: str
    content: str
    timestamp: int

    def to_bytes(self) -> bytes:
        return self.__definition__.encode(self)

    @classmethod
    def from_bytes(cls, payload: bytes) -> "TextMessage":
        return cls.__definition__.decode(cls, payload)

TextMessage.__definition__ = MessageDef(
    name="TextMessage",
    type_id=1001,
    topic="examples",
    fields=[
        FieldDef("sender", FixedStr(32)),
        FieldDef("content", FixedStr(256)),
        FieldDef("timestamp", Primitive.U64),
    ],
    dataclass=TextMessage,
)
register_message(TextMessage.__definition__)

