(* AUTO-GENERATED from contracts.yaml - DO NOT EDIT *)
(* Generated by mycelium-protocol codegen. *)
(* Edit contracts.yaml and rerun code generation. *)

[@@@ocaml.warning "-33"]

open Runtime

let schema_digest = Bytes.of_string "\x24\x7f\x6c\xcf\x85\x13\x67\x05\x72\x7c\xab\xc7\xba\x30\xd4\x32\x9a\x2a\x19\x4f\xc4\x31\xe4\x5f\x15\x7d\xc1\xcc\xc4\x73\xd1\xea"

module BatchOperation = struct
  type t = {
    operation_id: int64;
    items: bytes list;
    total_count: int;
  }

  let type_id = 1003
  let topic = "examples"

  let encode (msg : t) =
    let buf = Bytes.create 220 in
    let offset = 0 in
    let offset = Runtime.Primitive.encode_u64 buf offset msg.operation_id in
    let offset =
      Runtime.FixedVecBytes.encode_list
        buf offset msg.items ~element_size:20 ~capacity:10
    in
    let _offset = Runtime.Primitive.encode_u32 buf offset msg.total_count in
    buf

  let decode payload =
    let offset = 0 in
    let operation_id, offset = Runtime.Primitive.decode_u64 payload offset in
    let items, offset =
      Runtime.FixedVecBytes.decode_list payload offset ~element_size:20 ~capacity:10
    in
    let total_count, _offset = Runtime.Primitive.decode_u32 payload offset in
    { operation_id; items; total_count }
end

module CounterUpdate = struct
  type t = {
    counter_id: int64;
    value: int;
    delta: int;
  }

  let type_id = 1002
  let topic = "examples"

  let encode (msg : t) =
    let buf = Bytes.create 16 in
    let offset = 0 in
    let offset = Runtime.Primitive.encode_u64 buf offset msg.counter_id in
    let offset = Runtime.Primitive.encode_i32 buf offset msg.value in
    let _offset = Runtime.Primitive.encode_i32 buf offset msg.delta in
    buf

  let decode payload =
    let offset = 0 in
    let counter_id, offset = Runtime.Primitive.decode_u64 payload offset in
    let value, offset = Runtime.Primitive.decode_i32 payload offset in
    let delta, _offset = Runtime.Primitive.decode_i32 payload offset in
    { counter_id; value; delta }
end

module TextMessage = struct
  type t = {
    sender: string;
    content: string;
    timestamp: int64;
  }

  let type_id = 1001
  let topic = "examples"

  let encode (msg : t) =
    let buf = Bytes.create 88 in
    let offset = 0 in
    let offset = Runtime.FixedStr.encode buf offset msg.sender ~capacity:32 in
    let offset = Runtime.FixedStr.encode buf offset msg.content ~capacity:256 in
    let _offset = Runtime.Primitive.encode_u64 buf offset msg.timestamp in
    buf

  let decode payload =
    let offset = 0 in
    let sender, offset = Runtime.FixedStr.decode payload offset ~capacity:32 in
    let content, offset = Runtime.FixedStr.decode payload offset ~capacity:256 in
    let timestamp, _offset = Runtime.Primitive.decode_u64 payload offset in
    { sender; content; timestamp }
end
